spring.application.name=72-food-delivery-backend
server.port=9194
spring.datasource.url=jdbc\:h2\:mem\:fooddb\n
spring.datasource.username=sa\n
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create\n
spring.jpa.show-sql=false\n
spring.h2.console.enabled=true\n
spring.h2.console.path=/h2-console
